[project]
name = "timeweaver"
version = "0.1.0"
description = "TimeWeaver — Predictive Writer & Personal Paper"
readme = "README.md"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
pythonpath = ["."]
